baseURL = 'https://davidgriffin99.github.io/nicolasventureswebsite02/'
languageCode = 'en-us'
title = 'Nicolas Ventures'
theme = 'nicolasventures-theme'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'About Us'
  url = '/about'
  weight = 2
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 3
